---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-a
spec:
  type: ClusterIP
  selector:
    app: echoserver
  ports:
    - port: 80
      name: http-echoserver-a
      targetPort: http-api-a
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-a
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        image: docker.io/solsson/http-echo:latest
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"
        ports:
        - name: http-api-a
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver-b
spec:
  type: ClusterIP
  selector:
    app: echoserver-secondary
  ports:
    - port: 80
      name: http-echoserver-b
      targetPort: http-api-b
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver-b
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: echoserver-secondary
  template:
    metadata:
      labels:
        app: echoserver-secondary
    spec:
      containers:
      - name: echoserver-seconday
        image: docker.io/solsson/http-echo:latest
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "80"
        ports:
        - name: http-api-b
          containerPort: 80
